### ISSUE TITLE
INCLUDE paging.tpl not functioning consistently.

### ISSUE THREAD

**Issue by dismalbliss** [Phorum/Core#885] opened 2012-09-07 11:52 UTC
On my phorum installation, we have started to experience seemingly random topics with multiple pages not including the paging within the topic, that is, on the read.tpl page. Instead of being able to advance from one page to the next while reading, we have to go back to the message list.tpl  as the paging is still seen next to the subject line there.

I am running 5.2.18

**Comment by oricgn** [comment] 2015-09-11 13:01
Can you give a link to a thread in your Phorum where this problem occurs?

**Comment by oricgn** [comment] 2015-09-18 20:36
My attempts to get in contact with dismalbliss were without success.

I'm not able to reproduce the problem.

Closing...

**Closed by oricgn** 2015-09-18 20:36 UTC
Labels: 5.2_-_Next_Stable
